server:
  port: 10041
  servlet:
    context-path: /demoNew

openapi:

   secretId:   # secretId
   secretKey: #’Àªßµƒ√‹‘ø
 

  publicKey:

  restURL:  https://10.6.140.2/openapi/queryData/ # queryUri
  responseCode: $.head.responseCode
  responseMsg: $.head.responseMsg
  response: $.response  #FRAI0001


logging:
  config:classpath:log4j2-spring.xml
